-- Run this if your students table already exists and needs the new columns
-- Skip if you're running schema.sql fresh

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS program_year VARCHAR(100) AFTER middle_name,
    ADD COLUMN IF NOT EXISTS birth_date DATE AFTER program_year,
    ADD COLUMN IF NOT EXISTS gender ENUM('Male','Female','Other') AFTER birth_date,
    ADD COLUMN IF NOT EXISTS ethnicity VARCHAR(100) AFTER gender,
    ADD COLUMN IF NOT EXISTS religion VARCHAR(100) AFTER ethnicity,
    ADD COLUMN IF NOT EXISTS civil_status VARCHAR(50) AFTER religion,
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(20) AFTER civil_status,
    ADD COLUMN IF NOT EXISTS personal_email VARCHAR(100) AFTER mobile_number,
    ADD COLUMN IF NOT EXISTS institutional_email VARCHAR(100) AFTER personal_email,
    ADD COLUMN IF NOT EXISTS permanent_address TEXT AFTER institutional_email,
    ADD COLUMN IF NOT EXISTS current_address TEXT AFTER permanent_address,
    ADD COLUMN IF NOT EXISTS mother_name VARCHAR(150) AFTER current_address,
    ADD COLUMN IF NOT EXISTS mother_birthday DATE AFTER mother_name,
    ADD COLUMN IF NOT EXISTS mother_ethnicity VARCHAR(100) AFTER mother_birthday,
    ADD COLUMN IF NOT EXISTS mother_religion VARCHAR(100) AFTER mother_ethnicity,
    ADD COLUMN IF NOT EXISTS mother_education VARCHAR(100) AFTER mother_religion,
    ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(100) AFTER mother_education,
    ADD COLUMN IF NOT EXISTS mother_company VARCHAR(100) AFTER mother_occupation,
    ADD COLUMN IF NOT EXISTS mother_income VARCHAR(50) AFTER mother_company,
    ADD COLUMN IF NOT EXISTS mother_contact VARCHAR(20) AFTER mother_income,
    ADD COLUMN IF NOT EXISTS father_name VARCHAR(150) AFTER mother_contact,
    ADD COLUMN IF NOT EXISTS father_birthday DATE AFTER father_name,
    ADD COLUMN IF NOT EXISTS father_ethnicity VARCHAR(100) AFTER father_birthday,
    ADD COLUMN IF NOT EXISTS father_religion VARCHAR(100) AFTER father_ethnicity,
    ADD COLUMN IF NOT EXISTS father_education VARCHAR(100) AFTER father_religion,
    ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(100) AFTER father_education,
    ADD COLUMN IF NOT EXISTS father_company VARCHAR(100) AFTER father_occupation,
    ADD COLUMN IF NOT EXISTS father_income VARCHAR(50) AFTER father_company,
    ADD COLUMN IF NOT EXISTS father_contact VARCHAR(20) AFTER father_income,
    ADD COLUMN IF NOT EXISTS parent_status VARCHAR(100) AFTER father_contact,
    ADD COLUMN IF NOT EXISTS num_siblings INT DEFAULT 0 AFTER parent_status,
    ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(150) AFTER num_siblings,
    ADD COLUMN IF NOT EXISTS guardian_address TEXT AFTER guardian_name,
    ADD COLUMN IF NOT EXISTS guardian_contact VARCHAR(20) AFTER guardian_address,
    ADD COLUMN IF NOT EXISTS hobbies TEXT AFTER guardian_contact,
    ADD COLUMN IF NOT EXISTS talents TEXT AFTER hobbies,
    ADD COLUMN IF NOT EXISTS sports TEXT AFTER talents,
    ADD COLUMN IF NOT EXISTS socio_civic TEXT AFTER sports,
    ADD COLUMN IF NOT EXISTS school_org TEXT AFTER socio_civic,
    ADD COLUMN IF NOT EXISTS hospitalized TINYINT(1) DEFAULT 0 AFTER school_org,
    ADD COLUMN IF NOT EXISTS hospitalized_details TEXT AFTER hospitalized,
    ADD COLUMN IF NOT EXISTS had_operation TINYINT(1) DEFAULT 0 AFTER hospitalized_details,
    ADD COLUMN IF NOT EXISTS operation_details TEXT AFTER had_operation,
    ADD COLUMN IF NOT EXISTS has_illness TINYINT(1) DEFAULT 0 AFTER operation_details,
    ADD COLUMN IF NOT EXISTS illness_details TEXT AFTER has_illness,
    ADD COLUMN IF NOT EXISTS common_illness TEXT AFTER illness_details,
    ADD COLUMN IF NOT EXISTS last_doctor_visit VARCHAR(100) AFTER common_illness,
    ADD COLUMN IF NOT EXISTS doctor_visit_reason TEXT AFTER last_doctor_visit,
    ADD COLUMN IF NOT EXISTS concern_fear TINYINT(1) DEFAULT 0 AFTER doctor_visit_reason,
    ADD COLUMN IF NOT EXISTS concern_communication TINYINT(1) DEFAULT 0 AFTER concern_fear,
    ADD COLUMN IF NOT EXISTS concern_shyness TINYINT(1) DEFAULT 0 AFTER concern_communication,
    ADD COLUMN IF NOT EXISTS concern_loneliness TINYINT(1) DEFAULT 0 AFTER concern_shyness,
    ADD COLUMN IF NOT EXISTS concern_stress TINYINT(1) DEFAULT 0 AFTER concern_loneliness,
    ADD COLUMN IF NOT EXISTS concern_anger TINYINT(1) DEFAULT 0 AFTER concern_stress,
    ADD COLUMN IF NOT EXISTS concern_self_confidence TINYINT(1) DEFAULT 0 AFTER concern_anger,
    ADD COLUMN IF NOT EXISTS concern_academic TINYINT(1) DEFAULT 0 AFTER concern_self_confidence,
    ADD COLUMN IF NOT EXISTS concern_career TINYINT(1) DEFAULT 0 AFTER concern_academic,
    ADD COLUMN IF NOT EXISTS concern_financial TINYINT(1) DEFAULT 0 AFTER concern_career,
    ADD COLUMN IF NOT EXISTS concern_others TEXT AFTER concern_financial;
